name: Build Windows 10 LTSC 2021 ISO
run-name: Build Windows 10 LTSC 2021 - amd64 ${{ github.event.inputs.lang || 'zh-cn' }}

on:
  workflow_dispatch:
    inputs:
      lang:
        description: Language pack
        required: true
        default: zh-cn
        type: choice
        options:
          - zh-cn
          - en-us
          - zh-tw
          - ja-jp
          - ko-kr
          - de-de
          - fr-fr
          - es-es
          - ru-ru
          - pt-br

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build-uup.yml
    with:
      target: win10-ltsc-2021
      arch: amd64
      lang: ${{ github.event.inputs.lang || 'zh-cn' }}
      all: false
